pocket_option:
  token: "your po token"

telegram:
  token: "your telegram token"
  channel_id: "your channel_id"

newsapi:
  key: "YOUR_NEWSAPI_KEY"

alpha_vantage:
  key: "your alpha_vamtage key"

huggingface:
  token: "you hf token"
